- GaeManda/Projects/Core/GMDExtensions/UITextField+Extension.swift
- GaeManda/Projects/Domain/Entity/Dog.swift
- GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditViewController.swift
- GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/Widgets/DogProfileEditScrollView.swift
- #31 
강아지 수정 ScrollView의 UI 프로퍼티들을 Private하고 설정하고, 
필요있는 이벤트, 프로퍼티는 Reactive Extension을 통해 
ViewController에서 접근할 수 있도록 수정하였습니다.
> 강아지 수정 ScrollView Reactive Extension 적용

- GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/Widgets/DogProfileEditScrollView.swift
- #36 
이전에 작업에서 버튼 바인딩이 빠져서 추가했습니다.
> 강아지 수정 ScrollView 버튼 바인딩

- GaeManda/Projects/App/Sources/LoggedIn/LoggedInComponent.swift
- GaeManda/Projects/Core/GMDExtensions/Notification+Extension.swift
- GaeManda/Projects/Core/GMDExtensions/UITextField+Extension.swift
- GaeManda/Projects/Core/GMDUtils/KeyboardListener.swift
- GaeManda/Projects/Domain/Entity/Message.swift
- GaeManda/Projects/Presentation/Chatting/Implementations/Chatting/ChattingBuilder.swift
- GaeManda/Projects/Presentation/Chatting/Implementations/Chatting/ChattingInteractor.swift
- GaeManda/Projects/Presentation/Chatting/Implementations/Chatting/ChattingRouter.swift
- GaeManda/Projects/Presentation/Chatting/Implementations/Chatting/ChattingViewController.swift
- GaeManda/Projects/Presentation/Chatting/Implementations/Chatting/MessageCellType.swift
- GaeManda/Projects/Presentation/Chatting/Implementations/Chatting/Widgets/ChattingCells/DateCell.swift
- GaeManda/Projects/Presentation/Chatting/Implementations/Chatting/Widgets/ChattingCells/ReceiveCell.swift
- GaeManda/Projects/Presentation/Chatting/Implementations/Chatting/Widgets/ChattingCells/ReceiveWithProfileImageCell.swift
- GaeManda/Projects/Presentation/Chatting/Implementations/Chatting/Widgets/ChattingCells/SendCell.swift
- GaeManda/Projects/Presentation/Chatting/Implementations/Chatting/Widgets/ChattingOptionsButton.swift
- GaeManda/Projects/Presentation/Chatting/Implementations/Chatting/Widgets/ChattingTextView.swift
- GaeManda/Projects/Presentation/Chatting/Implementations/ChattingListBuilder.swift
- GaeManda/Projects/Presentation/Chatting/Implementations/ChattingListInteractor.swift
- GaeManda/Projects/Presentation/Chatting/Implementations/ChattingListRouter.swift
- GaeManda/Projects/Presentation/Chatting/Implementations/ChattingListViewController.swift
- GaeManda/Projects/Presentation/Chatting/Implementations/Widgets/ChattingListCell.swift
- GaeManda/Projects/Presentation/Chatting/Interfaces/Chatting.swift
- GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/Widgets/DogProfileDashBoardCell.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/TermsOfUse/TermsOfUseCell/TermsOfUseCell.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/TermsOfUse/TermsOfUseViewController.swift
- #40
채팅방 UI작업 완료 
- `GMDNavigationItem`에 밑에 사진에 있는 버튼 타입 새로 추가해야 할꺼 같음!
> 채팅 UI 작업 - 채팅방 UI 작업

- GaeManda/Projects/Core/GMDExtensions/UIViewController+Extensions.swift
- GaeManda/Projects/Core/GMDUtils/FloatingTabBarPresentable.swift
- GaeManda/Projects/Core/GMDUtils/KeyboardListener.swift
- GaeManda/Projects/Core/Project.swift
- GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileInteractor.swift
- GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileViewController.swift
- #42 
User Profile Interactor 작업 및 코드 리팩토링
- 해당 리블렛에 강아지 Profile Interactor작업은 나중에 할 예정
> User Profile Interactor 작업

- GaeManda/Projects/DesignKit/Sources/Button/ConfirmButton.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/AddressSettingViewController.swift
- close #52 
- ConfirmButton 생성
- AddressSettingView 리팩토링
- feature/#52를 feature/#44에 머지 후 ConfirmButton를 적용하고 feature/#44를 main에 머지 할 예정입니다.
> AddressSettingView 리팩토링

- GaeManda/Projects/Core/GMDExtensions/UIViewController+Extensions.swift
- GaeManda/Projects/Data/DTO/Sources/DogDTO/DogResponseDTO.swift
- GaeManda/Projects/Data/DTO/Sources/UpdateDogDTO/UpdateDogRequestDTO.swift
- GaeManda/Projects/Data/DTO/Sources/UpdateDogDTO/UpdateDogResponseDTO.swift
- GaeManda/Projects/Data/RepositoryImpl/Sources/DogRepositoryImpl/DogAPI.swift
- GaeManda/Projects/Data/RepositoryImpl/Sources/DogRepositoryImpl/DogRepositoryImpl.swift
- GaeManda/Projects/Domain/Entity/Dog.swift
- GaeManda/Projects/Domain/Interfaces/Repository/DogReposiotry.swift
- GaeManda/Projects/Domain/Interfaces/UseCase/UserProfileUseCase.swift
- GaeManda/Projects/Domain/UseCaseImpl/Sources/UserProfileUseCaseImpl.swift
- GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditBuilder.swift
- GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditInteractor.swift
- GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditViewController.swift
- GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/ViewModel/DogDashBoardViewModel.swift
- GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/ViewModel/TextFieldModeViewModel.swift
- GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/Widgets/DogProfileDashBoardCell.swift
- GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/Widgets/DogProfileEditScrollView.swift
- GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileInteractor.swift
- GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileRouter.swift
- GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileViewController.swift
- GaeManda/Projects/Presentation/GMDProfile/Implementations/Widgets/DogsCollectionViewCell.swift
- GaeManda/Projects/Presentation/GMDProfile/Interfaces/DogProfileEdit.swift
- #51
강아지 수정 Interactor 작업입니다.
- "수정완료"버튼 클릭 시 특정 `TextField`에 작성이 안되어있으면 warningLabel을 띄우는데, 
해당 경우에 모든 textField를 `normal` 모드로 리셋을 하고, 작성이 안되어있는 것만 'warning'으로 변경할지, 
혹은, 'warning'은 그대로 두고, 새롭게 만족 안한것들을 추가적으로 'warning'으로 변경할지 상의해야할것 같습니다.
> 강아지 수정 Interactor 작업

- GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/AddressSettingViewController.swift
close #60
- `AddressSettingViewController` 키보드 리스너 수정 적용했습니다.
> AddressSettingViewController 키보드 리스너 수정 적용

- GaeManda/Projects/Core/GMDExtensions/String+Extension.swift
- GaeManda/Projects/Core/GMDExtensions/UITextField+Extension.swift
- GaeManda/Projects/Core/GMDUtils/Base/BaseViewController.swift
- GaeManda/Projects/Core/GMDUtils/KeyboardListener.swift
- GaeManda/Projects/Domain/Entity/Dog.swift
- GaeManda/Projects/Presentation/Chatting/Implementations/Chatting/ChattingViewController.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/AddressSettingViewController.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/SecondDogSetting/SecondDogSettingViewController.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/ThirdDogSetting/ThirdDogSettingViewController.swift
close #59 
SecondDogSettingViewController 리팩토링입니다.
|스크린샷|동영상|
|:---:|:---:|
|<img src="https://github.com/WalkingDogWithFriends/GaeManDa/assets/48887389/7b82224f-4b62-4cf1-807a-153e281b8b39" width="375"/>|<img src="https://github.com/WalkingDogWithFriends/GaeManDa/assets/48887389/5d5c20a2-7835-4489-9efd-7b156bdf4f91" width="375"/>|
> SecondDogSettingViewController 리팩토링

- GaeManda/Projects/Core/GMDExtensions/String+Extension.swift
- GaeManda/Projects/Core/GMDExtensions/UITextField+Extension.swift
- GaeManda/Projects/Core/GMDUtils/Base/BaseViewController.swift
- GaeManda/Projects/Core/GMDUtils/KeyboardListener.swift
- GaeManda/Projects/Domain/Entity/Dog.swift
- GaeManda/Projects/Presentation/Chatting/Implementations/Chatting/ChattingViewController.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/AddressSettingViewController.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/FirstDogSetting/FirstDogSettingViewController.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/SecondDogSetting/SecondDogSettingViewController.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/ThirdDogSetting/ThirdDogSettingViewController.swift
close #58 
FirstDogSettingViewController 리팩토링입니다.
작업 사진 있으면 추가
|스크린샷|동영상|
|:---:|:---:|
|<img src="https://github.com/WalkingDogWithFriends/GaeManDa/assets/48887389/73b85387-b15a-450d-92e1-6bfc465e365e" width="375"/>|<img src="https://github.com/WalkingDogWithFriends/GaeManDa/assets/48887389/efe23c24-9270-4441-98cb-c33e59774db6" width="375"/>|
> FirstDogSettingViewController 리팩토링

- GaeManda/Projects/Core/GMDExtensions/String+Extension.swift
- GaeManda/Projects/Core/GMDExtensions/UITextField+Extension.swift
- GaeManda/Projects/Core/GMDUtils/Base/BaseViewController.swift
- GaeManda/Projects/Core/GMDUtils/KeyboardListener.swift
- GaeManda/Projects/DesignKit/Sources/Button/ConfirmButton.swift
- GaeManda/Projects/DesignKit/Sources/UnderLineTextField.swift
- GaeManda/Projects/Domain/Entity/Dog.swift
- GaeManda/Projects/Presentation/Chatting/Implementations/Chatting/ChattingViewController.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/AddressSettingViewController.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/FirstDogSetting/FirstDogSettingViewController.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/SecondDogSetting/SecondDogSettingViewController.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/ThirdDogSetting/ThirdDogSettingViewController.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/UserSetting/UserSettingViewController.swift
close #57 
유저 프로필 화면 리팩토링
|스크린샷|동영상|
|:---:|:---:|
|<img src="https://github.com/WalkingDogWithFriends/GaeManDa/assets/48887389/6bcf76f0-4f4b-4ca8-932c-6254096c6450" width="375"/>|<img src="https://github.com/WalkingDogWithFriends/GaeManDa/assets/48887389/9e7eb32f-0885-4c44-9997-91ed60970bb1" width="375"/>|
> 유저 프로필 화면 리팩토링

- GaeManda/Projects/Core/Project.swift
- GaeManda/Projects/Data/DTO/Sources/DogDTO/DogResponseDTO.swift
- GaeManda/Projects/Data/DTO/Sources/NewDogDTO/NewDogRequestDTO.swift
- GaeManda/Projects/Data/DTO/Sources/NewDogDTO/NewDogResponseDTO.swift
- GaeManda/Projects/Data/DTO/Sources/UpdateDogDTO/UpdateDogRequestDTO.swift
- GaeManda/Projects/Data/RepositoryImpl/Sources/DogRepositoryImpl/DogAPI.swift
- GaeManda/Projects/Data/RepositoryImpl/Sources/DogRepositoryImpl/DogRepositoryImpl.swift
- GaeManda/Projects/Domain/Entity/Dog.swift
- GaeManda/Projects/Domain/Interfaces/Repository/DogReposiotry.swift
- GaeManda/Projects/Domain/Interfaces/UseCase/UserProfileUseCase.swift
- GaeManda/Projects/Domain/UseCaseImpl/Sources/UserProfileUseCaseImpl.swift
- GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditInteractor.swift
- GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditViewController.swift
- GaeManda/Projects/Presentation/GMDProfile/Implementations/NewDogProfile/NewDogProfileBuilder.swift
- GaeManda/Projects/Presentation/GMDProfile/Implementations/NewDogProfile/NewDogProfileInteractor.swift
- GaeManda/Projects/Presentation/GMDProfile/Implementations/NewDogProfile/NewDogProfileViewController.swift
- GaeManda/Projects/Presentation/GMDProfile/Implementations/Widgets/DogsCollectionViewCell.swift
- #73
강아지 추가 Interactor Mock 서버와 연결
> 강아지 프로필 추가 Interactor 로직 작업

- GaeManda/Projects/App/Sources/AppRootComponent.swift
- GaeManda/Projects/App/Sources/LoggedOut/LoggedOutBuilder.swift
- GaeManda/Projects/App/Sources/LoggedOut/LoggedOutComponent.swift
- GaeManda/Projects/App/Sources/LoggedOut/LoggedOutInteractor.swift
- GaeManda/Projects/App/Sources/LoggedOut/LoggedOutRouter.swift
- GaeManda/Projects/Presentation/SignIn/Implementations/SignInBuilder.swift
- GaeManda/Projects/Presentation/SignIn/Implementations/SignInInteractor.swift
- GaeManda/Projects/Presentation/SignIn/Implementations/SignInViewController.swift
> SignIn 리블렛 수정 및 UI작업

- GaeManda/Projects/Core/GMDExtensions/PHPickerResult+Extension.swift
- GaeManda/Projects/Core/GMDUtils/UIViewController+Utils.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/FirstDogSetting/FirstDogSettingViewController.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/UserSetting/UserSettingViewController.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/Widgets/OnBoardingView.swift
close #67 
이미지 선택 기능을 구현합니다.
https://github.com/WalkingDogWithFriends/GaeManDa/assets/48887389/81cbfa57-8816-4643-8c2d-421fd0e2919a
- PHPickerViewController을 사용했습니다.
> 이미지 선택 기능 구현

- GaeManda/Projects/Core/GMDExtensions/String+Extension.swift
- GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditInteractor.swift
- GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditViewController.swift
- GaeManda/Projects/Presentation/GMDProfile/Implementations/NewDogProfile/NewDogProfileInteractor.swift
- GaeManda/Projects/Presentation/GMDProfile/Implementations/NewDogProfile/NewDogProfileViewController.swift
- GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileEdit/UserProfileEditInteractor.swift
- GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileEdit/UserProfileEditViewController.swift
- GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileInteractor.swift
- GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileRouter.swift
- GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileViewController.swift
- GaeManda/Projects/Presentation/GMDProfile/Interfaces/DogProfileEdit.swift
- GaeManda/Projects/Presentation/GMDProfile/Interfaces/NewDogProfile.swift
- GaeManda/Projects/Presentation/GMDProfile/Interfaces/UserProfileEdit.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/AddressSettingInteractor.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/AddressSettingViewController.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/DogSettingInteractor.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/DogSettingRouter.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/FirstDogSetting/FirstDogSettingInteractor.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/FirstDogSetting/FirstDogSettingViewController.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/SecondDogSetting/SecondDogSettingInteractor.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/SecondDogSetting/SecondDogSettingViewController.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/ThirdDogSetting/ThirdDogSettingInteractor.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/ThirdDogSetting/ThirdDogSettingViewController.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/OnBoardingInteractor.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/OnBoardingRouter.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/UserSetting/UserSettingInteractor.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/UserSetting/UserSettingViewController.swift
- GaeManda/Projects/Presentation/OnBoarding/Interfaces/AddressSetting.swift
- GaeManda/Projects/Presentation/OnBoarding/Interfaces/DogSetting.swift
- GaeManda/Projects/Presentation/OnBoarding/Interfaces/UserSetting.swift
- #95 
Swipe 를 통해 뒤로가는 기능 구현했습니다.
> Swipe back 제스쳐 적용

- GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditViewController.swift
- GaeManda/Projects/Presentation/GMDProfile/Implementations/NewDogProfile/NewDogProfileViewController.swift
- GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileEdit/UserProfileEditViewController.swift
- #94 
GMDProfile 이미지 선택 기능 적용
> GMDProfile 이미지 선택 기능 적용

- GaeManda/Projects/Core/GMDUtils/Base/BaseViewController.swift
- GaeManda/Projects/Core/GMDUtils/GMDTextFieldListener/GMDTextFieldListener.swift
- GaeManda/Projects/Core/GMDUtils/PassTouchesScrollView/PassTouchesScrollView.swift
- GaeManda/Projects/Core/GMDUtils/PassTouchesScrollView/PassTouchesScrollViewDelegate.swift
- GaeManda/Projects/DesignKit/Sources/DropDown/DropDownListener.swift
- GaeManda/Projects/DesignKit/Sources/DropDown/DropDownTableView.swift
- GaeManda/Projects/DesignKit/Sources/DropDown/DropDownView.swift
- GaeManda/Projects/DesignKit/Sources/TextField/GMDTextField.swift
- GaeManda/Projects/DesignKit/Sources/TextField/UnderLineTextField.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/FirstDogSetting/FirstDogSettingViewController.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/SecondDogSetting/SecondDogSettingViewController.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/SecondDogSetting/SecondDogSettingViewModel.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/Widgets/OnBoardingView.swift
- #104
강아지 설정 UI작업 완료했습니다. 
`UIScrollView`에서 `touchesBegan`이벤트가 안되는 관계로 
`PassTouchesSrcollView`와 `PassTouchesSrcollViewDelegate`를 구현했습니다. 
|첫번째 강아지 설정|두번째 강아지 설정|
|:---:|:---:|
|<img src="https://github.com/WalkingDogWithFriends/GaeManDa/assets/81402827/4097cb3a-a150-4976-9f9a-bd90351448a2" width="200"/>|<img src="https://github.com/WalkingDogWithFriends/GaeManDa/assets/81402827/4821ada7-23e2-4bdd-9ce9-1c026e6bc7cc" width="200"/>|
> 온보딩 강아지 설정 UI작업 완료

- GaeManda/Projects/DesignKit/Sources/Button/ConfirmButton.swift
- GaeManda/Projects/DesignKit/Sources/Button/GMDOptionButton.swift
- GaeManda/Projects/DesignKit/Sources/DropDown/DropDownView.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/FirstDogSetting/FirstDogSettingViewController.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/SecondDogSetting/SecondDogSettingViewController.swift
> 온보딩 강아지 설정 UI 로직

- GaeManda/.swiftlint.yml
- GaeManda/Projects/GMDClustering/Project.swift
- GaeManda/Projects/GMDClustering/Sources/Cluster.swift
- GaeManda/Projects/GMDClustering/Sources/Clustering.swift
- GaeManda/Projects/GMDClustering/Sources/Dummy.swift
- GaeManda/Projects/GMDClustering/Sources/KMeans.swift
- GaeManda/Projects/GMDClustering/Sources/LinkdedList/LinkedList.swift
- GaeManda/Projects/GMDClustering/Sources/LinkdedList/Node.swift
- GaeManda/Projects/GMDClustering/Sources/Model/ClusterResult.swift
- GaeManda/Projects/GMDClustering/Sources/Model/Location.swift
- GaeManda/Projects/Presentation/GMDMap/Project.swift
- GaeManda/Tuist/ProjectDescriptionHelpers/TargetDependency+Extension.swift
- GaeManda/Workspace.swift
- #131 
Clustering API구현 완료 했습니다. 
|클러스터링 이전|클러스터링 이후|영상|
|:---:|:---:|:---:|
|<img src="https://github.com/jungseokyoung-cloud/Clustering/assets/81402827/313923a5-c026-47c5-aec7-19cd4eba38d9" width="200"/>|<img src="https://github.com/jungseokyoung-cloud/Clustering/assets/81402827/eef60c27-a7a9-48aa-9554-5c494593c8e0" width="200"/>|<img src="https://github.com/WalkingDogWithFriends/GaeManDa/assets/81402827/27f8c028-e1bf-4654-8484-2bdae93c96b6" width="200"/>|
사용법은 다음과 같습니다. 
Clustering할 데이터모델에 `ClusterData`를 채택해준 후, `Location`변수를 구현해줍니다. 
```Swift 
struct Person: ClusterData {
let id: Int
let name: String
let location: Location
}
```
Clustering을 결과를 받아볼 객체에 `ClusteringDelegate`를 채택합니다.
이후 Clustering할 데이터의 타입을 명시해주고, Clustering의 `delegate`를 `self`로 지정합니다.
``` Swift
import Clustering
final …
```
> GMDClustering API 구현

- GaeManda/Projects/Data/GMDNetwork/EncodingType.swift
- GaeManda/Projects/Data/GMDNetwork/MultipartFormData/MultipartEncoding.swift
- GaeManda/Projects/Data/GMDNetwork/MultipartFormData/MultipartFormDataBody.swift
- GaeManda/Projects/Data/GMDNetwork/TargetType.swift
- GaeManda/Projects/Data/GMDNetwork/TaskType.swift
> MultipartFormData 구현

- GaeManda/Projects/Core/GMDUtils/Cache/Cache.swift
- GaeManda/Projects/Core/GMDUtils/Cache/ImageLoader.swift
- GaeManda/Projects/Core/GMDUtils/Cache/UIImageView+Cache.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/UserProfileSetting/UserProfileSettingInteractor.swift
- #152 
간단하게 캐싱하여 이미지를 로드하는 이미지 뷰 Extension을 구현했습니다.
`imageView.loadImage(urlString:)` 형태이고 이미지의 Url을 넣으면 비동기적으로 알아서 가져옵니다~!
n/a
n/a
> 이미지 캐싱 및 다운로더 구현

- GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/AddressSettingViewController.swift
- GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/Views/LocationSearchButton.swift
- #161 
주소 설정 버튼 구현했습니다.
|아이폰8|아이폰14프로|
|:---:|:---:|
|<img width="375" src="https://github.com/WalkingDogWithFriends/GaeManDa/assets/48887389/36143530-f8f6-47a5-acc1-5ca827685dc4"/>|<img width="375" src="https://github.com/WalkingDogWithFriends/GaeManDa/assets/48887389/112a2830-fa92-419d-88ad-298573320991"/>
- 없슴둥
close #161
> 주소 설정 버튼 구현
